config/routes.rb
Rails.application.routes.draw do

  resources :photos
  resources :w_tasks
  get 'login/index'
  get 'login/user'
  get 'user/new'
  post 'login/auth'
  resources :oneweeks do
    get 'search', on: :collection
  end
  resources :tasks 
  resources :chatlogs  
  resources :group_tasks 
  resources :groups 
  resources :user_groups 
  resources :users 
  resources :fin_tasks 
  resources :often_tasks

end

app/models/chatlog.rb
class Chatlog < ActiveRecord::Base
  default_scope -> {order(created_at: :desc)}
end

app/models/fin_task.rb
class FinTask < ActiveRecord::Base
end

app/models/g_login.rb
class GLogin < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :reviews
    def self.authenticate(user_name, password)
        gro = find_by(name: name)
    if gro != nil && gro.name == name then
        gro
    else
        return
    end
  end
end

app/models/group_task.rb
class GroupTask < ActiveRecord::Base
end

app/models/often_task.rb
class OftenTask < ActiveRecord::Base
has_many :tasks
end

app/models/oneweek.rb
class Oneweek < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader

end

app/models/task.rb
class Task < ActiveRecord::Base
belongs_to :often_task
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :reviews
    def self.authenticate(user_name, mailadd)
        usr = find_by(user_name: user_name)
    if usr != nil && usr.mailadd == mailadd then
        usr
    else
        return
    end
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  def change
    create_table :files do |t|
      t.string :upload_file_name
      t.binary :upload_file
      
      t.timestamps
    end
  end
end

app/controllers/fin_tasks_controller.rb
class FinTasksController < ApplicationController
  before_action :set_fin_task, only: [:show, :edit, :update, :destroy]

  # GET /fin_tasks
  # GET /fin_tasks.json
  def index
    @fin_tasks = FinTask.all
  end

  # GET /fin_tasks/1
  # GET /fin_tasks/1.json
  def show
  end

  # GET /fin_tasks/new
  def new
    @fin_task = FinTask.new
  end

  # GET /fin_tasks/1/edit
  def edit
  end

  # POST /fin_tasks
  # POST /fin_tasks.json
  def create
    @fin_task = FinTask.new(fin_task_params)

    respond_to do |format|
      if @fin_task.save
        format.html { redirect_to @fin_task, notice: '作成完了！' }
        format.json { render :show, status: :created, location: @fin_task }
      else
        format.html { render :new }
        format.json { render json: @fin_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fin_tasks/1
  # PATCH/PUT /fin_tasks/1.json
  def update
    respond_to do |format|
      if @fin_task.update(fin_task_params)
        format.html { redirect_to @fin_task, notice: '編集完了！' }
        format.json { render :show, status: :ok, location: @fin_task }
      else
        format.html { render :edit }
        format.json { render json: @fin_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fin_tasks/1
  # DELETE /fin_tasks/1.json
  def destroy
    @fin_task.destroy
    respond_to do |format|
      format.html { redirect_to fin_tasks_url, notice: '削除完了！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fin_task
      @fin_task = FinTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fin_task_params
      params.require(:fin_task).permit(:fin_day, :task_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatlogs_helper.rb
module ChatlogsHelper
end

app/helpers/fin_tasks_helper.rb
module FinTasksHelper
end

app/helpers/g_login_helper.rb
module GLoginHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/oneweeks_helper.rb
module OneweeksHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/w_tasks_helper.rb
module WTasksHelper
end

app/views/fin_tasks/_form.html.erb
<%= form_for(@fin_task) do |f| %>
  <% if @fin_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fin_task.errors.count, "error") %> prohibited this fin_task from being saved:</h2>

      <ul>
      <% @fin_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :終了日 %><br>
    <%= f.date_select :fin_day %>
  </div>
  <div class="field">
    <%= f.label :タスク名 %><br>
    <%= f.text_field :task_id %>
  </div>
  <div class="actions">
    <%= f.submit :タスク終了 %>
  </div>
<% end %>

app/views/fin_tasks/edit.html.erb
<div style="position:absolute; top:100px; left:655px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:775px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:895px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1015px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1135px;">
<a href="">
 <%= image_tag 'btn057_03.png' %>
 </div>
</a>
<div style="position:absolute; top:180px; left:870px;">

<h1>更新</h1>

<%= render 'form' %>

<%= link_to '詳細', @fin_task %> |
<%= link_to '戻る', fin_tasks_path %>
<%= link_to 'マイページ', tasks_path %>

app/views/fin_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div style="position:absolute; top:100px; left:655px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:775px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:895px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1015px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1135px;">
<a href="">
 <%= image_tag 'btn057_03.png' %>
 </div>
</a>

<div style="position:absolute; top:180px; left:870px;">

<h1>完了したタスク</h1>

<table>
  <thead>
    <tr>
      <th>終了日</th>
      <th>予定名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fin_tasks.each do |fin_task| %>
      <tr>
        <td><%= fin_task.fin_day %></td>
        <td><%= fin_task.task_id %></td>
        <td><%= link_to '詳細', fin_task %></td>
        <td><%= link_to '更新', edit_fin_task_path(fin_task) %></td>
        <td><%= link_to '削除', fin_task, method: :delete, data: { confirm: '削除してもよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '追加', new_fin_task_path %>
<%= link_to 'マイページ', tasks_path %>

app/views/fin_tasks/new.html.erb
<div style="position:absolute; top:100px; left:655px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:775px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:895px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1015px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1135px;">
<a href="">
 <%= image_tag 'btn057_03.png' %>
 </div>
</a>

<div style="position:absolute; top:180px; left:870px;">

<h1>追加</h1>

<%= render 'form' %>

<%= link_to '戻る', fin_tasks_path %>
<%= link_to 'マイページ', tasks_path %>

app/views/fin_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div style="position:absolute; top:100px; left:655px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:775px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:895px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1015px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1135px;">
<a href="">
 <%= image_tag 'btn057_03.png' %>
 </div>
</a>
<div style="position:absolute; top:250px; left:900px;">

<p>
  <strong>終了日:</strong>
  <%= @fin_task.fin_day %>
</p>

<p>
  <strong>タスク名:</strong>
  <%= @fin_task.task_id %>
</p>

<%= link_to '更新', edit_fin_task_path(@fin_task) %> |
<%= link_to '戻る', fin_tasks_path %>