config/routes.rb
Rails.application.routes.draw do

  resources :photos
  resources :w_tasks
  get 'login/index'
  get 'login/user'
  get 'user/new'
  post 'login/auth'
  resources :oneweeks do
    get 'search', on: :collection
  end
  resources :tasks 
  resources :chatlogs  
  resources :group_tasks 
  resources :groups 
  resources :user_groups 
  resources :users 
  resources :fin_tasks 
  resources :often_tasks

end

app/models/chatlog.rb
class Chatlog < ActiveRecord::Base
  default_scope -> {order(created_at: :desc)}
end

app/models/fin_task.rb
class FinTask < ActiveRecord::Base
end

app/models/g_login.rb
class GLogin < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :reviews
    def self.authenticate(user_name, password)
        gro = find_by(name: name)
    if gro != nil && gro.name == name then
        gro
    else
        return
    end
  end
end

app/models/group_task.rb
class GroupTask < ActiveRecord::Base
end

app/models/often_task.rb
class OftenTask < ActiveRecord::Base
has_many :tasks
end

app/models/oneweek.rb
class Oneweek < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader

end

app/models/task.rb
class Task < ActiveRecord::Base
belongs_to :often_task
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :reviews
    def self.authenticate(user_name, mailadd)
        usr = find_by(user_name: user_name)
    if usr != nil && usr.mailadd == mailadd then
        usr
    else
        return
    end
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  def change
    create_table :files do |t|
      t.string :upload_file_name
      t.binary :upload_file
      
      t.timestamps
    end
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.all
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create
  upload_file = content_params[:upload_file]
  file = {}
  if upload_file != nil
    file[:upload_file] = upload_file.read
    file[:upload_file_name] = upload_file_original_filename
  end
  file[:password] = file_params[:password]
  @file = File.new(file)
  respond_to do |format|
    if @file.save
      format.html {redirect_to @content,notice: 'Upload success' }
      format.json {render action: 'show', status: :created, location: @content }
    else
      @file = File.all
      format.html {render action: 'index' }
      format.json {render json: @content.errors, status: :unprocessable_entity}
    end
  end
end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: '編集完了！' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: '削除完了！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:user_id, :group_id)
    end
end

app/helpers/chatlogs_helper.rb
module ChatlogsHelper
end

app/helpers/fin_tasks_helper.rb
module FinTasksHelper
end

app/helpers/g_login_helper.rb
module GLoginHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/oneweeks_helper.rb
module OneweeksHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/w_tasks_helper.rb
module WTasksHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
      <% @user_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.text_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<div style="position:absolute; top:100px; left:660px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:900px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1020px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1140px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<h1>Editing User Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<div style="position:absolute; top:180px; left:800px;">

<p id="notice"><%= notice %></p>

<div style="position:absolute; top:100px; left:660px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>


<div style="position:absolute; top:100px; left:900px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1020px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1140px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<h1>Listing User Groups</h1>

<table>
<%= form_for(@file) do %>
  <div class="field">
    <%= f.file_field :upload_file %>
  </div>
  <div class="actions"
    <%= f.submit "Upload" %>
  </div>
<% end %>
</table>

<br>

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/new.html.erb
<div style="position:absolute; top:100px; left:660px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:900px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1020px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1140px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>


<h1>New User Group</h1>

<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<div style="position:absolute; top:100px; left:660px;">
<a href="http://localhost:3000/tasks/new">
 <%= image_tag 'btn057_01.png' %>
  </div>
  </a>

<div style="position:absolute; top:100px; left:900px;">
 <a href="http://localhost:3000/oneweeks">
 <%= image_tag 'btn057_05.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1020px;">
 <a href="http://localhost:3000/often_tasks">
 <%= image_tag 'btn057_06.png' %>
 </div>
</a>

<div style="position:absolute; top:100px; left:1140px;">
<a href="http://localhost:3000/chatlogs">
 <%= image_tag 'btn057_08.png' %>
 </div>
</a>

<div style="position:absolute; top:250px; left:900px;">

<p>
  <strong>User:</strong>
  <%= @user_group.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user_group.group_id %>
</p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>