config/routes.rb
Rails.application.routes.draw do

  resources :photos
  resources :w_tasks
  get 'login/index'
  get 'login/user'
  get 'user/new'
  post 'login/auth'
  resources :oneweeks do
    get 'search', on: :collection
  end
  resources :tasks 
  resources :chatlogs  
  resources :group_tasks 
  resources :groups 
  resources :user_groups 
  resources :users 
  resources :fin_tasks 
  resources :often_tasks

end

app/models/chatlog.rb
class Chatlog < ActiveRecord::Base
  default_scope -> {order(created_at: :desc)}
end

app/models/fin_task.rb
class FinTask < ActiveRecord::Base
end

app/models/g_login.rb
class GLogin < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :reviews
    def self.authenticate(user_name, password)
        gro = find_by(name: name)
    if gro != nil && gro.name == name then
        gro
    else
        return
    end
  end
end

app/models/group_task.rb
class GroupTask < ActiveRecord::Base
end

app/models/often_task.rb
class OftenTask < ActiveRecord::Base
has_many :tasks
end

app/models/oneweek.rb
class Oneweek < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :image, ImageUploader

end

app/models/task.rb
class Task < ActiveRecord::Base
belongs_to :often_task
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :reviews
    def self.authenticate(user_name, mailadd)
        usr = find_by(user_name: user_name)
    if usr != nil && usr.mailadd == mailadd then
        usr
    else
        return
    end
  end
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  def change
    create_table :files do |t|
      t.string :upload_file_name
      t.binary :upload_file
      
      t.timestamps
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_logined

  # GET /users
  # GET /users.json

  def index
    @users = User.all
  end

  # GET /users/
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '登録ありがとうございます!!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '更新が完了しました!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '削除が完了しました' }
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:user_name, :mailadd)
  end
  def auth
    name = 'migi'
    passwd = 'hidari'
     authenticate_or_request_with_http_basic('ユーザー一覧') do |n,p|
      n == name && p == passwd
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatlogs_helper.rb
module ChatlogsHelper
end

app/helpers/fin_tasks_helper.rb
module FinTasksHelper
end

app/helpers/g_login_helper.rb
module GLoginHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/oneweeks_helper.rb
module OneweeksHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/w_tasks_helper.rb
module WTasksHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ユーザーネーム %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :メールアドレス %><br>
    <%= f.text_field :mailadd %>
  </div>
  <div class="actions">
    <%= f.submit :作成 %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>今日だけすることを教えてください</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :今日だけすること %><br>
    <%= f.text_field :user_name %>
  </div>
<% end %>

<%= link_to '次へ', @user %> |
<%= link_to '戻る', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ユーザー</h1>

<table>
  <thead>
    <tr>
      <th>ユーザーネーム</th>
      <th>メールアドレス</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.mailadd %></td>
        <td><%= link_to '詳細', user %></td>
        <td><%= link_to '更新', edit_user_path(user) %></td>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: '本当に削除してもいいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_user_path %>

app/views/users/new.html.erb
<h1>ようこそ、PerfectToDoGOへ！！</h1>
<br>
<h1>あなたの名前とメールアドレスを教えてください</h1>
<br><br><br>
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div style="position:absolute; top:150px; left:900px;">

<p>
  <strong>ユーザーネーム:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong>メールアドレス</strong>
  <%= @user.mailadd %>
</p>

<%= link_to '戻る', tasks_path %>